### ISSUE TITLE
Could we share our work here?

### ISSUE THREAD

**Issue by WindVChen** [bcmi/Awesome-Image-Harmonization#6]
Hello there,

This repository is truly fantastic! I've been closely following the works listed here, and they've been a great source of inspiration for me.

I was wondering if it would be possible for us to be honored with the opportunity to share our recent open-source project in your esteemed repository. Our project is a harmonization method based on Implicit Neural Representation, allowing it to process images with any aspect ratio and resolution.

Here's some information about our project. We genuinely hope you could consider featuring our work alongside these impressive projects:

### Dense Pixel-to-Pixel Harmonization via Continuous Image Representation

Jianqi Chen, Yilan Zhang, Zhengxia Zou, Keyan Chen, and Zhenwei Shi

[![](https://img.shields.io/badge/arXiv-2303.01681-b31b1b.svg)](https://arxiv.org/abs/2303.01681)
<a href="https://huggingface.co/spaces/WindVChen/INR-Harmon"><img alt="Huggingface" src="https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-INR Harmonization-orange"></a>

Paper: https://huggingface.co/papers/2303.01681
Github: https://github.com/WindVChen/INR-Harmonization
Demo (Huggingface Space): https://huggingface.co/spaces/WindVChen/INR-Harmon

Thank you for your time and consideration. Looking forward to hearing from you soon.

Best regards

**Comment by ustcnewly** [comment]
Done. Nice work.

**Comment by WindVChen** [comment]
Thanks a million!
